### ISSUE TITLE
!rave doesn't work well with quotations

### ISSUE THREAD

**Issue by kspalm** [ClemsonCPSC-Discord/ClemBot#202] opened 2020-10-30 02:35 UTC
ClemBot returns an error when the string for !rave has quotations (which is a Discord issue from what I understand), but when the quotation marks are escaped with \\, the \\'s show up in the gif. For example, if someone invokes the command with "!rave What\'s up?", the gif includes the \\. The command should recognize when the escape character (\\) is used and remove it from the string accordingly. This way people can use the command with escaped quotations but not have the \\'s appear in the gif.

**Comment by Jay-Madden** [comment] 2020-10-30 03:12
This is not actually a clembot problem, its a discord.py/discord problem, quoted strings are a way for the command parser to differentiate command arguments. as far as i know there is no fix due to parser ambiguities

**Comment by kspalm** [comment] 2020-10-30 03:17
I know the quotation thing is a discord.py problem, I was just suggesting removing escape characters manually if someone uses them for !rave. I don't think it'd be a difficult fix.

**Comment by Jay-Madden** [comment] 2020-10-30 03:21
the problem is WHERE do you remove the characters, the command isnt invoked at all if the parser errors out. its all done internally by d.py and thrown to the global error handler

**Comment by Jay-Madden** [comment] 2020-10-30 03:22
There are a few hacky ways to handle the error globally and reinvoke the command but none of them are particularly palatable to me

**Comment by kspalm** [comment] 2020-10-30 03:23
I'm talking about removing instances of '\', not the characters being escaped.

**Comment by kspalm** [comment] 2020-10-30 04:11
Updated original post to hopefully make what I'm talking about clearer.

**Comment by Jay-Madden** [comment] 2020-10-31 04:19
ahh noted, ya easy change probably

**Comment by Jay-Madden** [comment] 2020-11-27 04:32
fixed in #215

**Closed by Jay-Madden** 2020-11-27 04:32 UTC
Labels: bug, help wanted
